name: Docker for Linux builds
on:
  push:
    paths:
      - 'linux-build/**'
    branches:
      - master
      - main
      - dev
    tags:
      - '*'
  pull_request:
    paths:
      - 'linux-build/**'

env:
  DOCKER_IMAGE_NAME: ghcr.io/noxworld-dev/docker-build

jobs:
  linux_builder:
    name: Build the Linux docker image
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Log in to the GHCR.IO
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          docker pull $DOCKER_IMAGE_NAME:latest-linux && $(exit 0)
          cd ./linux-build
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $DOCKER_IMAGE_NAME:latest-linux -t $DOCKER_IMAGE_NAME:tmp-linux .

      - name: Push
        run: |
          docker tag $DOCKER_IMAGE_NAME:tmp-linux $DOCKER_IMAGE_NAME:latest-linux
          docker push $DOCKER_IMAGE_NAME:latest-linux
